config/routes.rb
Rails.application.routes.draw do

  get 'loadings/index'
  get 'loadings/show_all'
  get 'loadings/show_by_order'
  get 'loadings/show_by_location'
  resources :loadings do
    put :load_check, on: :member
    put :quality_check, on: :member
  end


  resources :locations
  resources :truck_histories
  resources :trucks
  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'
  get '/show'	=> 'orders#show'
  get '/routes/history' => 'routes#history'
  get '/orders/show_all' => 'orders#show_all'

  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:new, :create, :show]
  resources :routes do
    put :delivered, on: :member
    put :not_delivered, on: :member
    put :not_loaded, on: :member
    put :loaded, on: :member
  end



  devise_for :users
  get 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get 'users/:id' => 'users#show', as: :user
  resources :users

  root 'storefront#index'

  namespace :admin do
    resources :products do
      put :per_item, on: :member
      put :per_item_remove, on: :member
      put :per_pound, on: :member
      put :per_pound_remove, on: :member
      put :per_case, on: :member
      put :per_case_remove, on: :member
    end
    resources :brands
    resources :categories
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  include Subtotal
  has_many :line_items, dependent: :destroy



  def add_product(product_id)
    product = Product.find(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product: product, price: product.price)
    end
    return current_item
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order
  belongs_to :loading

  def total_price
    price * quantity
  end

end

app/models/location.rb
class Location < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  include Subtotal
  belongs_to :user
  has_many :line_items, dependent: :destroy
  has_many :routes


  PAYMENT_TYPES = ['Credit Card', 'Check', 'COD', 'Cash', 'PayPal']
  validates :name, :address, :pay_type, :user_id, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil 
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  has_many :line_items
  belongs_to :location
  before_destroy :ensure_not_referenced_by_any_line_item

  has_attached_file :avatar,
  styles: {
  medium: "300x300#",
  thumb: "100x100" },
  default_url: "missing_:style.jpg"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_size :avatar, less_than: 3.megabytes, unless: Proc.new { |m| m[:avatar_file_name].blank?}

  validates_presence_of :name, :brand_id, :category_id, :location_id
  validates_numericality_of :price, greater_than_or_equal_to: 0
  validates_numericality_of :quantity, greater_than_or_equal_to: 0

  def self.search_by_name_or_description(string)
    where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%" )
  end

  private 

  #ensure no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'lines items present')
      return false
    end
  end

end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :order
  belongs_to :truck

  validates_presence_of :order_id, :truck_id
end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :routes
  validates_presence_of :number, :description
end

app/models/truck_history.rb
class TruckHistory < ApplicationRecord
  belongs_to :truck
  has_attached_file :document, styles: {thumbnail: "60x60#"}
  validates_attachment :document, content_type: { content_type: "application/pdf" }
  validates_presence_of :maintenance_date, :maintenance_info, :truck_id
  validates :maintenance_passing, inclusion: {in: [true, false]}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:index]
  def index

    if params[:search]
      @products = Product.search_by_name_or_description(params[:search])
      if @products.empty?
	flash.now[:notice] = "No Result found for \"#{params[:search]}\", showing all products"
	@products = Product.all
      end

    elsif params[:cat_id]
      @category = Category.find(params[:cat_id])
      @products = Product.where(category_id: params[:cat_id])
    else
    @products = Product.all
    end


  end

  def about
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/loadings_helper.rb
module LoadingsHelper
  def quality_check
    @item = LineItem.find(params[:id])
    if @item.quality_check == true
      @item.update_columns({quality_check: false, quality_check_by: nil, quality_check_on: nil})
      @item.save
      redirect_to(:back)
    else
      @item.update_columns({quality_check: true, quality_check_by: current_user.email, quality_check_on: Time.now})
      @item.save
      redirect_to(:back)
    end
  end
  def load_check
    @item = LineItem.find(params[:id])
    if @item.check == true
      @item.update_columns({check: false, check_by: nil, check_on: nil})
      @item.save
      redirect_to(:back)
    else
      @item.update_columns({check: true, check_by: current_user.email, check_on: Time.now})
      @item.save
      redirect_to(:back)
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  # per item is 1, 3, 5, 7
  def per_item
    @product = Product.find(params[:id])
    @product.item_amount_type += 1
    @product.save
    render :edit
  end
  def per_item_remove
    @product = Product.find(params[:id])
    @product.item_amount_type -= 1
    @product.save
    render :edit
  end

  # per pound is 2, 3, 6, 7
  def per_pound
    @product = Product.find(params[:id])
    @product.item_amount_type += 2
    @product.save
    render :edit
  end
  def per_pound_remove
    @product = Product.find(params[:id])
    @product.item_amount_type -= 2
    @product.save
    render :edit
  end

  #per case is 4, 5, 6, 7
  def per_case
    @product = Product.find(params[:id])
    @product.item_amount_type += 4
    @product.save
    render :edit
  end
  def per_case_remove
    @product = Product.find(params[:id])
    @product.item_amount_type -= 4
    @product.save
    render :edit
  end

end

app/helpers/routes_helper.rb
module RoutesHelper
  def not_delivered
    @route = Route.find(params[:id])
    @route.update_attributes(delivered: false)
    @route.update_attributes(delivered_on: nil)
    redirect_to routes_path
  end

  def delivered
    @route = Route.find(params[:id])
    @route.update_attributes(delivered: true)
    @route.update_attributes(delivered_on: Time.now)
    redirect_to routes_path
  end

  def not_loaded
    @route = Route.find(params[:id])
    @route.update_attributes(truck_loaded: false)
    @route.update_attributes(truck_loaded_on: nil)
    redirect_to routes_path
  end

  def loaded
    @route = Route.find(params[:id])
    @route.update_attributes(truck_loaded: true)
    @route.update_attributes(truck_loaded_on: Time.now)
    redirect_to routes_path
  end
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/storefront/_cart.html.erb
<div class="col-sm-6 col-md-4 col-lg-3 panel panel-default panel-body">


<h2>Your shopping cart </h2>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
	<th>Product</th>
	<th>Quantity</th>
	<th></th>
      </tr>
    </thead>

      <%= render 'cart_items' %>


  </table>



  <div class="pull-right">
    <%= link_to fa_icon("angle-up", text: "Open Cart"), edit_cart_path, class: "btn btn-info btn-sm"  %>
    <%= link_to fa_icon("times-circle", text: "Empty Cart"), @cart, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm"  %>
  </div>

</div>

app/views/storefront/_cart_items.html.erb
    <tbody class="vertical-align">
      <% @cart.line_items.each do |product| %>
	<tr>
	  <td>
	    <%= product.product.name %>
	    <%= image_tag product.product.avatar.url(:thumb) %>
	  </td>
	  <td>
	    <div class="row">
	      <div class="col-md-2 col-lg-3">
	    <%= simple_form_for(product) do |f| %>
	      <%= f.input :quantity, input_html: { min: 0, style: 'width:60px' }, label: false, class: "pull-left"  %>
	      <%= f.button :submit, "Apply", :class => "btn-primary" %>
	    <% end %>
	      </div>
	    </div>
	  </td>
	  <td>
	    <%= link_to fa_icon("times-circle", text: "Remove"), line_item_path(product.id), method: :delete, class: "btn btn-sm btn-danger vertical-align" %>
	  </td>
	</tr>
      <% end %>
	<th></th>
    </tbody>

app/views/storefront/about.html.erb
	  
<h1>Storefront#about</h1>
<p>Find me in app/views/storefront/about.html.erb</p>

app/views/storefront/create.js.erb
$('#task').hide();

app/views/storefront/destroy.js.erb
$('#tasks').html("<%= j (render 'cart_item') %>");
$('#tasks').slideDown(350);

app/views/storefront/index.html.erb
<!-- ***************** -->
<!-- search bar        -->
<!-- ***************** -->
<span class="pull-right">
  <%= form_tag(shop_path, method: :get, role: "search", class: "form-inline") do  %>
    <div class="form-group">
      <%# TODO: hide the search label %>
      <%# label_tag :search class: "sr-only" %>
      <%= text_field_tag(:search, nil, placheholder: "Search Products", class: "form-control input-sm") %>
    </div>
    <%= submit_tag(:search, class: "btn btn-default btn-sm", style: "margin-right:20px;" ) %>
  <% end %>
</span>

<h1>Welcome to the Stor-tastic!</h1>
<p>Where all of your awesome products dreams come true</p>

<% if params[:cat_id] %>
  <h3>
    <%= @category.name.capitalize %>
    </h3>
  <% else %>
    <h3>
      All Products
    </h3>
  </h3>
<% end %>


<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6 col-md-8 col-lg-9 panel panel-default panel-body">

    <% @products.each do |product| %>
      <div class="col-xs-6 col-sm-4 col-md-2">
	<div class="">
	  <p>
	    <div class="text-center">
	      <br>
	      <br>
	      <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
	      <%= image_tag product.avatar.url(:thumb) %>
	      <h4><%# number_to_currency(product.price) %></h4>
		<h4>
		      <%= product.name %>
		</h4>
	      </a>
	      <%= button_to "Add to cart", line_items_path(product_id: product), class: "btn btn-sm btn-success", remote: true %>
	      <br>
	      <br>
	    </div>
	  </p>
	</div>
      </div>


      <!-- Modal -->
      <div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
	    <div class="modal-header">
	      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	      <h4 class="modal-title" id="myModalLabel"><%= product.name %></h4>
	    </div>
	    <div class="modal-body">
	      <p>
	      <%= image_tag product.avatar.url(:medium) %>
	      </p>
	      <p>
	      <%= number_to_currency(product.price) %>
	      </p>
	      <p>
	      <%= product.description %>
	      </p>
	    </div>
	    <div class="modal-footer">
	      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      <%= button_to "Add to cart", line_items_path(product_id: product), class: "btn btn-sm btn-success", remote: true %>
	    </div>
	  </div>
	</div>
      </div>

    <% end %>

    </div> <!--end panel body -->
	    <%= render 'cart' %>
  </div>

</div>

app/views/storefront/update.js.erb
$('#tasks').html("<%= j (render 'cart_items') %>");

$('#tasks').slideUp(350);