config/routes.rb
Rails.application.routes.draw do

  get 'loadings/index'
  get 'loadings/show_all'
  get 'loadings/show_by_order'
  get 'loadings/show_by_location'
  resources :loadings do
    put :load_check, on: :member
    put :quality_check, on: :member
  end


  resources :locations
  resources :truck_histories
  resources :trucks
  get '/shop' => 'storefront#index'
  get '/about' => 'storefront#about'
  get '/show'	=> 'orders#show'
  get '/routes/history' => 'routes#history'
  get '/orders/show_all' => 'orders#show_all'

  resource :cart, only: [:edit, :update, :destroy]
  resources :line_items, only: [:create, :destroy, :update]
  resources :orders, only: [:new, :create, :show]
  resources :routes do
    put :delivered, on: :member
    put :not_delivered, on: :member
    put :not_loaded, on: :member
    put :loaded, on: :member
  end



  devise_for :users
  get 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  get 'users/:id' => 'users#show', as: :user
  resources :users

  root 'storefront#index'

  namespace :admin do
    resources :products do
      put :per_item, on: :member
      put :per_item_remove, on: :member
      put :per_pound, on: :member
      put :per_pound_remove, on: :member
      put :per_case, on: :member
      put :per_case_remove, on: :member
    end
    resources :brands
    resources :categories
    resources :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  has_many :line_items
  belongs_to :location
  before_destroy :ensure_not_referenced_by_any_line_item

  has_attached_file :avatar,
  styles: {
  medium: "300x300#",
  thumb: "100x100" },
  default_url: "missing_:style.jpg"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates_attachment_size :avatar, less_than: 3.megabytes, unless: Proc.new { |m| m[:avatar_file_name].blank?}

  validates_presence_of :name, :brand_id, :category_id, :location_id
  validates_numericality_of :price, greater_than_or_equal_to: 0
  validates_numericality_of :quantity, greater_than_or_equal_to: 0

  def self.search_by_name_or_description(string)
    where("name LIKE ? OR description LIKE ?", "%#{string}%", "%#{string}%" )
  end

  private 

  #ensure no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'lines items present')
      return false
    end
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  include ProductsHelper
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /products
  # GET /products.json
  def index
    if params[:search]
      @products = Product.search_by_name_or_description(params[:search])
      if @products.empty?
	flash[:notice] = "No results found for \"#{params[:search]}\", showing all products instead"
	@products = Product.paginate(page: params[:page], per_page: 3)
      end

    elsif params[:cat_id]
      @category = Category.find(params[:cat_id])
      @products = Product.where(category_id: params[:cat_id])
    else
    @products = Product.paginate(page: params[:page], per_page: 3)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    # When creating a new item if price or quantity exists change item_amount_type 
    @product = Product.new(product_params)
     if @product.quantity != nil || @product.price != nil
       @product.item_amount_type +=1
     end
     if @product.pounds != nil || @product.price_per_pound != nil
       @product.item_amount_type +=2
     end
     if @product.case != nil || @product.price_per_case != nil
       @product.item_amount_type +=4
     end

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :category_id, :brand_id, :avatar, :item_amount_type, :location_id, :case, :price_per_case, :pounds, :price_per_pound)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

  # per item is 1, 3, 5, 7
  def per_item
    @product = Product.find(params[:id])
    @product.item_amount_type += 1
    @product.save
    render :edit
  end
  def per_item_remove
    @product = Product.find(params[:id])
    @product.item_amount_type -= 1
    @product.save
    render :edit
  end

  # per pound is 2, 3, 6, 7
  def per_pound
    @product = Product.find(params[:id])
    @product.item_amount_type += 2
    @product.save
    render :edit
  end
  def per_pound_remove
    @product = Product.find(params[:id])
    @product.item_amount_type -= 2
    @product.save
    render :edit
  end

  #per case is 4, 5, 6, 7
  def per_case
    @product = Product.find(params[:id])
    @product.item_amount_type += 4
    @product.save
    render :edit
  end
  def per_case_remove
    @product = Product.find(params[:id])
    @product.item_amount_type -= 4
    @product.save
    render :edit
  end

end

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product], class: "form-inline") do |f| %>
  <%= f.error_notification %>

  <form class="form-inline" role="form">
    <div class="form-groups">
      <div class="col-sm-10">
	name
	<%= f.input :name, label: false, placeholder: "Name" %>


    <%= render 'form_product_amount_type' %>

	<% case @product.item_amount_type %>
	<% when 1, 3, 5, 7 %>
	  <%= f.input :price, input_html: { min: 0 }  %>
	  <%= f.input :quantity, input_html: { min: 0 }  %>
	<% end %>

	<% case @product.item_amount_type %>
	<% when 2, 3, 6, 7 %>
	  <%= f.input :price_per_pound, input_html: { min: 0 }  %>
	  <%= f.input :pounds, input_html: { min: 0 }  %>
	<% end %>

	<% case @product.item_amount_type %>
	<% when 4, 5, 6, 7 %>
	  <%= f.input :price_per_case, input_html: { min: 0 }  %>
	  <%= f.input :case, input_html: { min: 0 }  %>
	<% end %>


	<%= f.input :description %>
	<%= f.association :location, hint: 'Required', include_blank: false %>
	<%= f.association :category, hint: 'Required', include_blank: false %>
	<%= f.association :brand, hint: 'Required', include_blank: false %>

      </div>
      <p>
	<% if @product.avatar.exists? %>
	  <%= image_tag @product.avatar.url(:medium) %>
	<% end %>
      </p>
	<%= f.input :avatar, as: :file %>
    </div>

      <div class="form-actions">
	<%= f.button :submit %>
      </div>

  </form>

<% end %>

app/views/admin/products/_form_product_amount_type.html.erb
	<% if current_page?(new_admin_product_path) %>

	<% else %>

	<div class="container-fluid">
	  <div class="row">
	    <div class="col-md-4 text-center">
	    <br>
	      <% case @product.item_amount_type %>
	        <% when 0, 2, 4, 6 %>
		<%= link_to "Add Per Item", 
		  per_item_admin_product_path(@product),
		  class: 'btn btn-default',
		  method: :put
		  %>
		<% when 1, 3, 5, 7 %>
		<%= link_to "Remove Per Item", 
		  per_item_remove_admin_product_path(@product),
		  class: 'btn btn-danger',
		  method: :put
		  %>
	      <% end %>
	      <br>
	    </div>
  
	    <div class="col-md-4 text-center">
	    <br>
	      <% case @product.item_amount_type %>
		<% when 0, 1, 4, 5 %>
		<%= link_to "Add Per Pound", 
		  per_pound_admin_product_path(@product),
		  class: 'btn btn-default',
		  method: :put
		  %>
		<% when 2, 3, 6, 7 %>
		<%= link_to "Remove Per Pound", 
		  per_pound_remove_admin_product_path(@product),
		  class: 'btn btn-danger',
		  method: :put
		  %>
	      <% end %>
	      <br>
	    </div>

	    <div class="col-md-4 text-center">
	    <br>
	      <% case @product.item_amount_type %>
		<% when 0, 1, 2, 3 %>
		<%= link_to "Add Per Case", 
		  per_case_admin_product_path(@product),
		  class: 'btn btn-default',
		  method: :put
		  %>
		<% when 4, 5, 6, 7 %>
		<%= link_to "Remove Per Case", 
		  per_case_remove_admin_product_path(@product),
		  class: 'btn btn-danger',
		  method: :put
		  %>
	      <% end %>

	      <br>
	      <br>
	    </div>
	  </div>
	</div>

	<% end %>

app/views/admin/products/edit.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-8 col-sm-offset-3">

    <h1>Editing Product</h1>

    <%= render 'form', product: @product %>

    <%= link_to 'Show', admin_product_path(@product) %> |
    <%= link_to 'Back', admin_products_path %>

    </div>

  </div>
</div>

app/views/admin/products/index.html.erb
<!-- ### Search bar ### -->

<span class="pull-right">
  <%= form_tag(admin_products_path, method: :get, role: "search", class: "form-inline") do  %>
    <div class="form_group">
      <%# TODO: hide the search label %>
      <%# label_tag :search class: "sr-only" %>
      <%= text_field_tag(:search, nil, placheholder: "Search Products", class: "form-control input-sm") %>
    </div>
    <%= submit_tag(:search, class: "btn btn-default btn-sm") %>
  <% end %>
</span>

<h1>Products</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Category</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.category.try('name') %></td>
        <td><%= product.brand.try('name') %></td>
        <td><%= link_to fa_icon("eye", text: "show"), admin_product_path(product) %></td>
        <td><%= link_to fa_icon("pencil", text: "Edit"), edit_admin_product_path(product) %></td>
        <td><%= link_to fa_icon('trash', text: 'Destroy'), admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Product', new_admin_product_path, class: "btn btn-sm btn-success" %>
<div class="text-center">
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

app/views/admin/products/new.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-4 col-sm-offset-4">

    <h1>New Product</h1>

<%= simple_form_for([:admin, @product], class: "form-inline") do |f| %>
  <%= f.error_notification %>

  <form class="form-inline" role="form">
    <div class="form-groups">
      <div class="col-sm-10">
	name
	<%= f.input :name, label: false, placeholder: "Name" %>



	  <%= f.input :price, input_html: { min: 0 }  %>
	  <%= f.input :quantity, input_html: { min: 0 }  %>

	  <%= f.input :price_per_pound, input_html: { min: 0 }  %>
	  <%= f.input :pounds, input_html: { min: 0 }  %>

	  <%= f.input :price_per_case, input_html: { min: 0 }  %>
	  <%= f.input :case, input_html: { min: 0 }  %>


	<%= f.input :description %>
	<%= f.association :location, hint: 'Required' %>
	<%= f.association :category, hint: 'Required' %>
	<%= f.association :brand, hint: 'Required' %>

      </div>
      <p>
	<% if @product.avatar.exists? %>
	  <%= image_tag @product.avatar.url(:medium) %>
	<% end %>
      </p>
	<%= f.input :avatar, as: :file %>
    </div>

      <div class="form-actions">
	<%= f.button :submit %>
      </div>

  </form>

<% end %>

    <%= link_to 'Back', admin_products_path %>

    </div>

  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container-fluid">
  <div class="row">

    <div class="col-sm-4 col-sm-offset-4">


    <p>
      <%= image_tag @product.avatar.url(:medium) %>
    </p>
    <p>
      <strong>Name:</strong>
      <%= @product.name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@product.price) %>
    </p>

    <p>
      <strong>Quantity:</strong>
      <%= @product.quantity %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @product.description %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @product.category.try('name') %>
    </p>

    <p>
      <strong>Brand:</strong>
      <%= @product.brand.try('name') %>
    </p>

    <%= link_to 'Edit', edit_admin_product_path(@product) %> |
    <%= link_to 'Back', admin_products_path %>

    </div>

  </div>
</div>